ShopDeliveryApplication/Controllers/ProductCategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using ShopsDbEntities;
using System.Linq;

namespace ShopDeliveryApplication.Controllers
{
	public class ProductCategoriesController : CatalogController
	{
		public ProductCategoriesController(MainDbContext context) : base(context)
		{
		}

		public IActionResult Index(byte shopId)
		{
			ViewData["ShopId"] = shopId;
			var categories = _context.ProductCategories.ToArray();

			return View(categories);
		}
	}
}

ShopDeliveryApplication/Controllers/ProductSubCategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using ShopsDbEntities;
using System.Linq;

namespace ShopDeliveryApplication.Controllers
{
	public class ProductSubCategoriesController : CatalogController
	{
		public ProductSubCategoriesController(MainDbContext context) : base(context)
		{
		}

		public IActionResult Index(byte shopId, byte categoryId)
		{
			ViewData["ShopId"] = shopId;
			ViewData["CategoryId"] = categoryId;
			var subCategories = _context.ProductSubCategories.ToArray();

			return View(subCategories);
		}
	}
}

ShopDeliveryApplication/Views/ProductCategories/Index.cshtml
@using ShopsDbEntities
@model ProductDbCategory[]

<h1>Категории</h1>

@{ await Html.RenderPartialAsync("_GetCategories", Model); }

ShopDeliveryApplication/Views/ProductCategories/_GetCategories.cshtml
@using ShopsDbEntities
@model ProductDbCategory[]

@foreach (var category in Model)
{
	<div>
		<p>@category.Name</p>
		<a asp-controller="ProductSubCategories"
		   asp-route-shopId="@ViewData["ShopId"]"
		   asp-route-categoryId="@category.Id">
			<img src="@category.ImgUrl" />
		</a>
	</div>
}