ShopDeliveryApplication/Controllers/ProductCategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using ShopsDbEntities;
using System.Linq;

namespace ShopDeliveryApplication.Controllers
{
	public class ProductCategoriesController : CatalogController
	{
		public ProductCategoriesController(MainDbContext context) : base(context)
		{
		}

		public IActionResult Index(byte shopId)
		{
			ViewData["ShopId"] = shopId;
			var categories = _context.ProductCategories.ToArray();

			return View(categories);
		}
	}
}

ShopDeliveryApplication/Controllers/ShopsController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDeliveryApplication.Models;
using ShopsDbEntities;
using System.Diagnostics;
using System.Linq;

namespace ShopDeliveryApplication.Controllers
{
	public class ShopsController : CatalogController
	{
		public ShopsController(MainDbContext context) : base(context)
		{
		}

		public IActionResult Index()
		{
			var shops = _context.Shops.ToArray();

			return View(shops);
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
			=> View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
	}
}

ShopDeliveryApplication/Views/Shops/Index.cshtml
@using ShopsDbEntities
@model Shop[]

<h1>Магазины</h1>

@{ await Html.RenderPartialAsync("_GetShops", Model); }

ShopDeliveryApplication/Views/Shops/_GetShops.cshtml
@using ShopsDbEntities
@model Shop[]

@foreach (var shop in Model)
{
	<div>
		<p>@shop.Name</p>
		<a asp-controller="ProductCategories"
		   asp-route-shopId="@shop.Id">
			<img src="@shop.ImgUrl" />
		</a>
	</div>
}