ShopDeliveryApplication/Controllers/ShopsController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDeliveryApplication.Models;
using ShopsDbEntities;
using System.Diagnostics;
using System.Linq;

namespace ShopDeliveryApplication.Controllers
{
	public class ShopsController : CatalogController
	{
		public ShopsController(MainDbContext context) : base(context)
		{
		}

		public IActionResult Index()
		{
			var shops = _context.Shops.ToArray();

			return View(shops);
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
			=> View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
	}
}

ShopDeliveryApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - ShopDeliveryApplication</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/css/utils.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Shops" asp-action="Index">Доставка товаров из магазинов</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<a id="bucket-btn" class="nav-link text-dark" onclick="Bucket.goToBucketPage()">
					Корзина
				</a>
				@if (User.Identity.IsAuthenticated)
				{
					<p>@User.Identity.Name</p>
					<form method="post" asp-controller="Account" asp-action="Logout">
						<input class="btn" type="submit" value="Выход" />
					</form>
				}
				else
				{
					<a class="btn" asp-controller="Account" asp-action="Login">Вход</a>
					<a class="btn" asp-controller="Account" asp-action="Register">Регистрация</a>
				}
			</div>
		</nav>
	</header>

	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			<p>Keknul</p>
		</div>
	</footer>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/js/app.js"></script>
	<script src="~/js/bucket.js"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>